baseURL: https://fljd.in
theme: fljdin

params:
  author: Florent Jardin
  fediverse: "@fljdin@mastodon.tedomum.net"

rssLimit: 5
pagination:
  pagerSize: 5

ignoreLogs:
  - "warning-goldmark-raw-html"

permalinks:
  posts: /:year/:month/:day/:slug
  pages: /:slug

related:
  includeNewer: true
  threshold: 80
  toLower: false
  indices:
    - name: keywords
      weight: 100
    - name: tags
      weight: 80
    - name: categories
      weight: 50
    - name: date
      weight: 10

removePathAccents: true
pygmentsUseClasses: true

# i18n
languageCode: fr
defaultContentLanguage: fr

languages:
  fr:
    title: "Carnet de découvertes"
    languageCode: fr
    languageName: Français
    contentDir: content/fr
    weight: 1
    menu:
      navigation:
        - identifier: talks
          title: "Conférences"
          url: "/conferences"
          weight: 1
        - identifier: archives
          title: "Archives"
          url: "/archives"
          weight: 2
        - identifier: about
          title: "À propos"
          url: "/a-propos"
          weight: 3
  en:
    title: "Discovery notebook"
    languageCode: en
    languageName: English
    contentDir: content/en
    weight: 2
    menu:
      navigation:
        - identifier: talks
          title: "Talks"
          url: "/en/talks"
          weight: 1
        - identifier: archives
          title: "Archives"
          url: "/en/archives"
          weight: 2
        - identifier: about
          title: "About me"
          url: "/en/about"
          weight: 3
